apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-typescript-app
  labels:
    app: express-typescript
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-typescript
  template:
    metadata:
      labels:
        app: express-typescript
    spec:
      containers:
      - name: express-typescript
        image: trialtab8o4.jfrog.io/my-repo-docker/express-typescript-docker:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: express-typescript-service
spec:
  type: LoadBalancer
  selector:
    app: express-typescript
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
