# SecretProviderClass for CSI Driver
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jfrog-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "jfrog-credentials"
        objectType: "secretsmanager"

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-typescript-app
  labels:
    app: express-typescript
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-typescript
  template:
    metadata:
      labels:
        app: express-typescript
    spec:
      containers:
      - name: express-typescript
        image: trial1tq967.jfrog.io/my-docker-repo1-docker/express-typescript-docker:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true
      imagePullSecrets:
        - name: jfrog-docker-secret
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: jfrog-secrets
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: express-typescript-service
spec:
  type: LoadBalancer
  selector:
    app: express-typescript
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
