apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "my-docker-secret"
        objectType: "secretsmanager"
        objectKeys: ["JFROG_USERNAME", "JFROG_PASSWORD"]
    secretsManagerSecretId: my-docker-secret
    region: ap-south-1
