name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install dependencies using Yarn
      - name: Install Dependencies
        run: yarn install

      # Run lint and tests
      - name: Lint and Test
        run: yarn lint && yarn test

      # Build the project
      - name: Build Project
        run: yarn build

      # Set up JFrog CLI
      - name: Setup JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          ./jfrog config add artifactory-server \
            --url http://16.170.217.244:8081/artifactory \
            --user ${{ secrets.JFROG_USERNAME }} \
            --password ${{ secrets.JFROG_PASSWORD }} \
            --interactive=false

      # Docker login directly to Artifactory
      - name: Docker Login to Artifactory
        run: echo ${{ secrets.JFROG_PASSWORD }} | docker login http://16.170.217.244:8081 \
          --username ${{ secrets.JFROG_USERNAME }} --password-stdin
      

      # Build Docker image
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag 16.170.217.244:8081/example-repo-local/express-typescript-docker:latest

      # Push Docker image to JFrog Artifactory
      - name: Push Docker Image to JFrog
        run: docker push 16.170.217.244:8081/example-repo-local/express-typescript-docker:latest

      # Notify (Optional)
      # Uncomment and configure if you want notifications (e.g., Slack)
      # - name: Notify Slack
      #   uses: rtCamp/action-slack-notify@v2
      #   with:
      #     webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     message: "Successfully deployed Docker image to JFrog Artifactory."
      #     color: good
