name: CI Pipeline 

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for [skip ci]
        id: skip_check
        run: |
          if git log -1 --pretty=%s | grep -iqE '\[skip ci\]|\[ci skip\]'; then
            echo "SKIP_CI=true" >> $GITHUB_ENV
          else
            echo "SKIP_CI=false" >> $GITHUB_ENV
          fi

      - name: Login to JFrog Docker Registry
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          echo "$JFROG_PASSWORD" | docker login -u "$JFROG_USERNAME" --password-stdin jfafn.jfrog.io

      # Yarn Build
      - name: Install dependencies
        run: yarn install
      - name: Lint and Test
        run: yarn lint && yarn test
      - name: Build Project
        run: yarn build

      # SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v1.5
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: "https://sonarqube.omf.cloud"
        with:
          projectKey: ${{ secrets.SONARQUBE_PROJECT_KEY }}
          organization: ${{ secrets.SONARQUBE_ORGANIZATION }}

      # Publish Tag
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Deployment to Dev
      - name: Deploy to Dev
        if: contains(github.ref, 'alpha')
        env:
          DEPLOY_ENVIRONMENT: "dev"
        run: |
          docker pull "$DEFAULT_REPO/${{ github.sha }}:latest"
          docker tag "$DEFAULT_REPO/${{ github.sha }}:latest" "$DEFAULT_REPO/dev:latest"
          docker push "$DEFAULT_REPO/dev:latest"

      # Notify Slack
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "Deployment of ${{ github.sha }} to ${DEPLOY_ENVIRONMENT} succeeded"
          color: good
        if: success()
