name: CI/CD Pipeline

on:
  push:
    branches:
      - 'alpha'
      - 'beta'
      - 'next'
      - 'master'
      - 'v[0-9]+.[0-9]+.x'
    tags:
      - 'v*'
  pull_request:

env:
  DEFAULT_REPO: "jfafn.jfrog.io/omfauto-container"
  WEBAPP_DIST_FOLDER: "omf-d-webapp"
  SONAR_HOST_URL: "https://sonarqube.omf.cloud"
  SLACK_CHANNEL: "#auto-los-jenkins"
  SLACK_NOTIFY_BRANCHES: "alpha,beta,next,master"
  SLACK_DEPLOYMENT_CHANNEL: "#omf-auto-deployments"

jobs:
  skip-ci:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for [skip ci] in commit message
        run: |
          git log -1 --pretty=%s | grep -iqE "\[skip ci\]|\[ci skip\]"
          echo "SKIP_CI=true" >> $GITHUB_ENV || true
